# Generated by Django 5.1.5 on 2025-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
    ]
